Add the initial workarounds to build an experimental build

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20098,87 +20098,89 @@ fi
 
 fi
 
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for presence of POSIX-style sigsetjmp/siglongjmp" >&5
-printf %s "checking for presence of POSIX-style sigsetjmp/siglongjmp... " >&6; }
-if test ${bash_cv_func_sigsetjmp+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  if test "$cross_compiling" = yes
-then :
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: cannot check for sigsetjmp/siglongjmp if cross-compiling -- defaulting to $bash_cv_posix_signals" >&5
-printf "%s\n" "$as_me: WARNING: cannot check for sigsetjmp/siglongjmp if cross-compiling -- defaulting to $bash_cv_posix_signals" >&2;}
-     if test "$bash_cv_posix_signals" = "yes" ; then
-	bash_cv_func_sigsetjmp=present
-     else
-	bash_cv_func_sigsetjmp=missing
-     fi
+# sigsetjmp/siglongjmp requires porting to Cygwin
+#
+# { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for presence of POSIX-style sigsetjmp/siglongjmp" >&5
+# printf %s "checking for presence of POSIX-style sigsetjmp/siglongjmp... " >&6; }
+# if test ${bash_cv_func_sigsetjmp+y}
+# then :
+#   printf %s "(cached) " >&6
+# else $as_nop
+#   if test "$cross_compiling" = yes
+# then :
+#   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: cannot check for sigsetjmp/siglongjmp if cross-compiling -- defaulting to $bash_cv_posix_signals" >&5
+# printf "%s\n" "$as_me: WARNING: cannot check for sigsetjmp/siglongjmp if cross-compiling -- defaulting to $bash_cv_posix_signals" >&2;}
+#      if test "$bash_cv_posix_signals" = "yes" ; then
+# 	bash_cv_func_sigsetjmp=present
+#      else
+# 	bash_cv_func_sigsetjmp=missing
+#      fi
 
-else $as_nop
-  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
+# else $as_nop
+#   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+# /* end confdefs.h.  */
 
-#ifdef HAVE_UNISTD_H
-#include <unistd.h>
-#endif
-#include <sys/types.h>
-#include <signal.h>
-#include <setjmp.h>
-#include <stdlib.h>
+# #ifdef HAVE_UNISTD_H
+# #include <unistd.h>
+# #endif
+# #include <sys/types.h>
+# #include <signal.h>
+# #include <setjmp.h>
+# #include <stdlib.h>
 
-int
-main()
-{
-#if !defined (_POSIX_VERSION) || !defined (HAVE_POSIX_SIGNALS)
-exit (1);
-#else
+# int
+# main()
+# {
+# #if !defined (_POSIX_VERSION) || !defined (HAVE_POSIX_SIGNALS)
+# exit (1);
+# #else
 
-int code;
-sigset_t set, oset, nset;
-sigjmp_buf xx;
+# int code;
+# sigset_t set, oset, nset;
+# sigjmp_buf xx;
 
-/* get the mask */
-sigemptyset(&set);
-sigemptyset(&oset);
+# /* get the mask */
+# sigemptyset(&set);
+# sigemptyset(&oset);
 
-sigprocmask(SIG_BLOCK, (sigset_t *)NULL, &oset);
-/* paranoia -- make sure SIGINT is not blocked */
-sigdelset (&oset, SIGINT);
-sigprocmask (SIG_SETMASK, &oset, (sigset_t *)NULL);
+# sigprocmask(SIG_BLOCK, (sigset_t *)NULL, &oset);
+# /* paranoia -- make sure SIGINT is not blocked */
+# sigdelset (&oset, SIGINT);
+# sigprocmask (SIG_SETMASK, &oset, (sigset_t *)NULL);
 
-/* save it */
-code = sigsetjmp(xx, 1);
-if (code)
-{
-  sigprocmask(SIG_BLOCK, (sigset_t *)NULL, &nset);
-  /* could compare nset to oset here, but we just look for SIGINT */
-  if (sigismember (&nset, SIGINT))
-    exit(1);
-  exit(0);
-}
+# /* save it */
+# code = sigsetjmp(xx, 1);
+# if (code)
+# {
+#   sigprocmask(SIG_BLOCK, (sigset_t *)NULL, &nset);
+#   /* could compare nset to oset here, but we just look for SIGINT */
+#   if (sigismember (&nset, SIGINT))
+#     exit(1);
+#   exit(0);
+# }
 
-/* change it so that SIGINT is blocked */
-sigaddset(&set, SIGINT);
-sigprocmask(SIG_BLOCK, &set, (sigset_t *)NULL);
+# /* change it so that SIGINT is blocked */
+# sigaddset(&set, SIGINT);
+# sigprocmask(SIG_BLOCK, &set, (sigset_t *)NULL);
 
-/* and siglongjmp */
-siglongjmp(xx, 10);
-exit(1);
-#endif
-}
+# /* and siglongjmp */
+# siglongjmp(xx, 10);
+# exit(1);
+# #endif
+# }
 
-_ACEOF
-if ac_fn_c_try_run "$LINENO"
-then :
-  bash_cv_func_sigsetjmp=present
-else $as_nop
-  bash_cv_func_sigsetjmp=missing
-fi
-rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
-  conftest.$ac_objext conftest.beam conftest.$ac_ext
-fi
+# _ACEOF
+# if ac_fn_c_try_run "$LINENO"
+# then :
+#   bash_cv_func_sigsetjmp=present
+# else $as_nop
+#   bash_cv_func_sigsetjmp=missing
+# fi
+# rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
+#   conftest.$ac_objext conftest.beam conftest.$ac_ext
+# fi
 
-fi
+# fi
 
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $bash_cv_func_sigsetjmp" >&5
 printf "%s\n" "$bash_cv_func_sigsetjmp" >&6; }
